name: ReactOS Server AMD64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ReactOS Server AMD64
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install Ninja
        run: choco install -y ninja

      - name: Install Flex & Bison
        run: |
          curl -O https://svn.reactos.org/storage/vperevertkin/flexbison.7z || curl -OL https://web.archive.org/web/2025if_/https://svn.reactos.org/storage/vperevertkin/flexbison.7z
          7z x flexbison.7z -O${{ github.workspace }}\bin

          echo "${{ github.workspace }}\bin" | Out-File `
            -FilePath $env:GITHUB_PATH `
            -Encoding utf8 `
            -Append

          echo "BISON_PKGDATADIR=${{ github.workspace }}\bin\share\bison" |
            Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          echo "M4=${{ github.workspace }}\bin\m4.exe" |
            Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Activate MSVC AMD64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure problem matchers
        run: echo ::add-matcher::.github/workflows/problem-matcher.json

      - name: Configure
        run: |
          cmake -S . -B build `
            -G Ninja `
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=toolchain-msvc.cmake `
            -DARCH:STRING=amd64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DENABLE_ROSTESTS=1 `
            -DENABLE_ROSAPPS=1

      - name: Build
        run: |
          cmake --build build -- -k0

      - name: Generate ISO
        run: |
          cmake --build build --target bootcd

      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          name: reactos-server-amd64
          path: build/bootcd.iso
