name: ReactOS AMD64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ReactOS AMD64 Release
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Ninja
        shell: powershell
        run: |
          choco install ninja -y

      - name: Install Flex and Bison
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "https://svn.reactos.org/storage/vperevertkin/flexbison.7z" `
            -OutFile "$env:RUNNER_TEMP\flexbison.7z"

          7z x "$env:RUNNER_TEMP\flexbison.7z" `
            "-o$env:RUNNER_TEMP\flexbison" `
            -y

          "$env:RUNNER_TEMP\flexbison" | Out-File `
            -FilePath $env:GITHUB_PATH `
            -Encoding utf8 `
            -Append

          "BISON_PKGDATADIR=$env:RUNNER_TEMP\flexbison\share\bison" |
            Out-File `
              -FilePath $env:GITHUB_ENV `
              -Encoding utf8 `
              -Append

          "M4=$env:RUNNER_TEMP\flexbison\m4.exe" |
            Out-File `
              -FilePath $env:GITHUB_ENV `
              -Encoding utf8 `
              -Append

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Show build environment
        shell: cmd
        run: |
          cl
          cmake --version
          ninja --version
          bison --version
          flex --version

      - name: Configure ReactOS
        shell: cmd
        run: |
          cmake -S . -B build ^
            -G Ninja ^
            -DCMAKE_TOOLCHAIN_FILE=toolchain-msvc.cmake ^
            -DARCH=amd64 ^
            -DCMAKE_BUILD_TYPE=Release

      - name: Build ReactOS
        shell: cmd
        run: |
          cmake --build build -- -k0

      - name: Build bootcd ISO
        shell: cmd
        run: |
          cmake --build build --target bootcd

      - name: Upload bootcd ISO
        uses: actions/upload-artifact@v4
        with:
          name: reactos-amd64-release
          path: build/bootcd.iso
          if-no-files-found: error
